#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER='$HOME/Pictures/wallpapers/wallpaper_2.jpg'

swaybg --output '*' --mode fill --image "$WALLPAPER"
